---
title: Teklia - Doc-UFCN Demo
description: >-
  [TEKLIA](https://teklia.com/)â€™s Document Layout Analysis on historical documents. For modern documents, see [ocelus.teklia.com](https://ocelus.teklia.com).
examples:
  - hugging_face/resource/hugging_face_1.jpg
  - hugging_face/resource/hugging_face_2.jpg
  - hugging_face/resource/hugging_face_3.jpg
  - hugging_face/resource/hugging_face_4.jpg

models:
  - model_name: Teklia/doc-ufcn-generic-historical-line
    title: Doc-UFCN Generic historical line detection
    description: >-
      The [generic historical line detection model](https://huggingface.co/Teklia/doc-ufcn-generic-historical-line) predicts text lines from document images. Please select an image from the examples below or upload your own image!
    classes_colors:
      - green
  - model_name: Teklia/doc-ufcn-huginmunin-line
    title: Doc-UFCN Hugin-Munin line detection
    description: >-
      The [Hugin-Munin line detection model](https://huggingface.co/Teklia/doc-ufcn-huginmunin-line) predicts horizontal and vertical text lines from Hugin-Munin document images. Please select an image from the examples below or upload your own image!
    classes_colors:
      - green
      - blue
  - model_name: Teklia/doc-ufcn-generic-page
    title: Doc-UFCN Generic page detection
    description: >-
      The [generic page detection model](https://huggingface.co/Teklia/doc-ufcn-generic-page) predicts single pages from document images. Please select an image from the examples below or upload your own image!
    classes_colors:
      - green
